services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 2s
      timeout: 2s
      retries: 30
    networks:
      - todo_net

  app:
    image: ghcr.io/maximshmelyov/todo_dashboard/app:latest
    container_name: todo-dashboard-app
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo_net
      - edge

volumes:
  todo_pg_data:

networks:
  todo_net:
    driver: bridge
  edge:
    external: true
    name: edge
